<form  method="POST" class="needs-validation main" novalidate>
    <nav class="navbar navbar-expand-lg navbar-light bg-white navbar-shadow">
        <div class="navbar-multiline mr-auto">
            <span class="navbar-brand" href="#0">Product Collateral Editor</span>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="<?= $this->router->to('adminHome') ?>">Home</a></li>
                    <?php
                        $product_page = '#0';
                        if(module_exists('admin-product'))
                            $product_page = $this->router->to('adminProduct');
                    ?>
                    <li class="breadcrumb-item"><a href="<?= $product_page ?>">Product</a></li>
                    <li class="breadcrumb-item"><a href="<?= $this->router->to('adminProductCollateral') ?>">Collateral</a></li>
                    <li class="breadcrumb-item active" aria-current="page"><?= $subtitle ?></li>
                </ol>
            </nav>
        </div>
        <button class="btn btn-primary">Save</button>
    </nav>

    <div class="container p-3">
        <div class="row mb-3">
            <?= $form->csrfField('noob') ?>
            <div class="col-md-5">
                <div class="card">
                    <div class="card-body">
                        <?= $form->field('name'); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>